// Comprehensive global cloud providers database for FTS.Money Platform
export const CLOUD_PROVIDERS = [
    // TIER 1 - GLOBAL HYPERSCALERS
    {
        id: 'aws',
        name: 'Amazon Web Services (AWS)',
        country: 'United States',
        continent: 'North America',
        specialty: 'Global Leader - Broadest Coverage',
        description: 'Industry leader with 33 regions, 105 availability zones worldwide',
        regions: ['us-east', 'us-west', 'eu-west', 'eu-central', 'ap-southeast', 'ap-northeast', 'sa-east', 'ca-central', 'me-south', 'af-south'],
        tier: 'tier1',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Mission Critical', 'Global Coverage', 'Financial Compliance'],
        recommendationReason: 'Best-in-class global infrastructure with proven financial services compliance',
        avgCostPerMonth: 5000,
        supportedCurrencies: ['USD', 'EUR', 'GBP', 'JPY', 'CNY'],
        logo: '☁️'
    },
    {
        id: 'azure',
        name: 'Microsoft Azure',
        country: 'United States',
        continent: 'North America',
        specialty: 'Enterprise Integration - Microsoft Stack',
        description: 'Strong enterprise compliance and hybrid cloud capabilities',
        regions: ['eastus', 'westus', 'northeurope', 'westeurope', 'southeastasia', 'australiaeast'],
        tier: 'tier1',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Enterprise', 'Hybrid Cloud', 'Government'],
        recommendationReason: 'Excellent for enterprise compliance, sovereign cloud options',
        avgCostPerMonth: 4800,
        supportedCurrencies: ['USD', 'EUR', 'GBP'],
        logo: '⊞'
    },
    {
        id: 'gcp',
        name: 'Google Cloud Platform (GCP)',
        country: 'United States',
        continent: 'North America',
        specialty: 'AI/ML & Advanced Analytics',
        description: 'Leading in AI, machine learning, and payment processing technology',
        regions: ['us-central', 'us-east', 'europe-west', 'asia-southeast'],
        tier: 'tier1',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['AI/ML', 'Payment Processing', 'Real-time Analytics'],
        recommendationReason: 'Superior payment processing APIs and real-time fraud detection',
        avgCostPerMonth: 4500,
        supportedCurrencies: ['USD', 'EUR'],
        logo: '🔵'
    },

    // TIER 2 - REGIONAL LEADERS
    {
        id: 'alibaba',
        name: 'Alibaba Cloud',
        country: 'China',
        continent: 'Asia',
        specialty: 'Asia Pacific Dominance',
        description: 'Largest cloud provider in Asia with deep China penetration',
        regions: ['cn-hangzhou', 'cn-beijing', 'cn-shanghai', 'ap-southeast', 'ap-northeast'],
        tier: 'tier2',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['China Market', 'Asia Pacific', 'Cross-border Payments'],
        recommendationReason: 'Essential for China operations and Asian e-commerce integration',
        avgCostPerMonth: 3500,
        supportedCurrencies: ['CNY', 'USD', 'EUR'],
        logo: '🟠'
    },
    {
        id: 'tencent',
        name: 'Tencent Cloud (腾讯云)',
        country: 'China',
        continent: 'Asia',
        specialty: 'WeChat & Gaming Infrastructure',
        description: 'Deep integration with WeChat Pay and Chinese digital ecosystem',
        regions: ['ap-guangzhou', 'ap-beijing', 'ap-shanghai', 'ap-nanjing'],
        tier: 'tier2',
        pciDss: true,
        iso27001: false,
        financialServices: true,
        recommendedFor: ['WeChat Integration', 'Gaming', 'Social Payments'],
        recommendationReason: 'Direct WeChat Pay integration and massive user base access',
        avgCostPerMonth: 3200,
        supportedCurrencies: ['CNY', 'HKD'],
        logo: '🐧'
    },
    {
        id: 'huawei',
        name: 'Huawei Cloud (华为云)',
        country: 'China',
        continent: 'Asia',
        specialty: '5G & Edge Computing',
        description: 'Leading in 5G infrastructure and telecom-grade reliability',
        regions: ['cn-north', 'cn-east', 'cn-south', 'ap-southeast'],
        tier: 'tier2',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Telecom', '5G Edge', 'IoT Payments'],
        recommendationReason: '5G-enabled edge computing for ultra-low latency transactions',
        avgCostPerMonth: 3000,
        supportedCurrencies: ['CNY', 'USD'],
        logo: '📡'
    },
    {
        id: 'ovhcloud',
        name: 'OVHcloud',
        country: 'France',
        continent: 'Europe',
        specialty: 'European Sovereignty',
        description: 'Largest European cloud provider with GDPR-native architecture',
        regions: ['eu-west', 'eu-central', 'ca-east'],
        tier: 'tier2',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['GDPR Compliance', 'EU Data Sovereignty', 'European PSPs'],
        recommendationReason: 'Best European sovereign cloud option with competitive pricing',
        avgCostPerMonth: 2800,
        supportedCurrencies: ['EUR', 'USD', 'GBP'],
        logo: '🇫🇷'
    },
    {
        id: 'oracle',
        name: 'Oracle Cloud',
        country: 'United States',
        continent: 'North America',
        specialty: 'Database & Financial Systems',
        description: 'Enterprise-grade database and financial application hosting',
        regions: ['us-phoenix', 'us-ashburn', 'eu-frankfurt', 'ap-mumbai'],
        tier: 'tier2',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Banking', 'Core Banking Systems', 'Oracle Applications'],
        recommendationReason: 'Native Oracle database integration and banking expertise',
        avgCostPerMonth: 4000,
        supportedCurrencies: ['USD', 'EUR'],
        logo: '🔴'
    },

    // ASIA PACIFIC
    {
        id: 'ntt',
        name: 'NTT Communications',
        country: 'Japan',
        continent: 'Asia',
        specialty: 'Japanese Enterprise',
        description: 'Leading Japanese cloud with strong financial sector presence',
        regions: ['jp-tokyo', 'jp-osaka'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Japan Market', 'Japanese Banking', 'Local Compliance'],
        recommendationReason: 'Deep relationships with Japanese financial institutions',
        avgCostPerMonth: 3500,
        supportedCurrencies: ['JPY', 'USD'],
        logo: '🇯🇵'
    },
    {
        id: 'naver',
        name: 'Naver Cloud',
        country: 'South Korea',
        continent: 'Asia',
        specialty: 'Korean E-commerce',
        description: 'Dominant in Korean market with Naver Pay integration',
        regions: ['kr-seoul'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Korea Market', 'Naver Pay', 'K-commerce'],
        recommendationReason: 'Essential for Korean PSPs and Naver ecosystem',
        avgCostPerMonth: 2500,
        supportedCurrencies: ['KRW', 'USD'],
        logo: '🇰🇷'
    },
    {
        id: 'singtel',
        name: 'Singtel Cloud',
        country: 'Singapore',
        continent: 'Asia',
        specialty: 'ASEAN Connectivity',
        description: 'Regional connectivity across Southeast Asia',
        regions: ['sg-singapore'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Singapore', 'ASEAN', 'Regional Payments'],
        recommendationReason: 'Excellent ASEAN network connectivity and local banking ties',
        avgCostPerMonth: 2800,
        supportedCurrencies: ['SGD', 'USD'],
        logo: '🇸🇬'
    },
    {
        id: 'tata',
        name: 'Tata Communications',
        country: 'India',
        continent: 'Asia',
        specialty: 'Indian Market Leader',
        description: 'Largest Indian cloud provider with RBI compliance',
        regions: ['in-mumbai', 'in-chennai', 'in-hyderabad'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['India Market', 'RBI Compliance', 'UPI Integration'],
        recommendationReason: 'RBI-approved infrastructure with UPI gateway access',
        avgCostPerMonth: 2000,
        supportedCurrencies: ['INR', 'USD'],
        logo: '🇮🇳'
    },
    {
        id: 'telkom',
        name: 'Telkom Indonesia',
        country: 'Indonesia',
        continent: 'Asia',
        specialty: 'Indonesia National Cloud',
        description: 'National telco with government cloud contracts',
        regions: ['id-jakarta'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Indonesia', 'Government', 'Local PSPs'],
        recommendationReason: 'Required for Indonesian data localization laws',
        avgCostPerMonth: 1800,
        supportedCurrencies: ['IDR', 'USD'],
        logo: '🇮🇩'
    },

    // MIDDLE EAST
    {
        id: 'stc',
        name: 'STC Cloud (Saudi)',
        country: 'Saudi Arabia',
        continent: 'Middle East',
        specialty: 'Saudi Banking Infrastructure',
        description: 'SAMA-approved cloud for Saudi financial services',
        regions: ['sa-riyadh', 'sa-jeddah'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Saudi Arabia', 'SAMA Compliance', 'Islamic Finance'],
        recommendationReason: 'SAMA-certified with Sharia-compliant hosting options',
        avgCostPerMonth: 3200,
        supportedCurrencies: ['SAR', 'USD'],
        logo: '🇸🇦'
    },
    {
        id: 'etisalat',
        name: 'Etisalat Cloud (UAE)',
        country: 'United Arab Emirates',
        continent: 'Middle East',
        specialty: 'UAE Financial Hub',
        description: 'Dubai financial free zone certified infrastructure',
        regions: ['ae-dubai', 'ae-abudhabi'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['UAE', 'DIFC Compliance', 'Middle East Hub'],
        recommendationReason: 'DIFC-certified for Dubai International Financial Centre',
        avgCostPerMonth: 3500,
        supportedCurrencies: ['AED', 'USD'],
        logo: '🇦🇪'
    },

    // EUROPE
    {
        id: 'stackit',
        name: 'STACKIT (Sovereign)',
        country: 'Germany',
        continent: 'Europe',
        specialty: 'German Sovereign Cloud',
        description: 'Schwarz Group sovereign cloud for German data residency',
        regions: ['de-germany'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Germany', 'BaFin Compliance', 'Data Sovereignty'],
        recommendationReason: 'Only sovereign cloud meeting strict German banking regulations',
        avgCostPerMonth: 4000,
        supportedCurrencies: ['EUR'],
        logo: '🇩🇪'
    },
    {
        id: 'exoscale',
        name: 'Exoscale (Swiss)',
        country: 'Switzerland',
        continent: 'Europe',
        specialty: 'Swiss Banking Standards',
        description: 'Swiss sovereign cloud with banking-grade security',
        regions: ['ch-zurich', 'ch-geneva'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Switzerland', 'Private Banking', 'FINMA Compliance'],
        recommendationReason: 'Swiss privacy laws and banking sector expertise',
        avgCostPerMonth: 4500,
        supportedCurrencies: ['CHF', 'EUR'],
        logo: '🇨🇭'
    },
    {
        id: 'hetzner',
        name: 'Hetzner',
        country: 'Germany',
        continent: 'Europe',
        specialty: 'Cost-Effective European',
        description: 'Budget-friendly German hosting with excellent performance',
        regions: ['de-falkenstein', 'de-nuremberg', 'fi-helsinki'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Cost Optimization', 'SME PSPs', 'Development'],
        recommendationReason: 'Best price-performance ratio in Europe',
        avgCostPerMonth: 1000,
        supportedCurrencies: ['EUR'],
        logo: '💰'
    },

    // LATIN AMERICA
    {
        id: 'ascenty',
        name: 'Ascenty (Brazil)',
        country: 'Brazil',
        continent: 'South America',
        specialty: 'Brazilian Data Centers',
        description: 'Largest Brazilian data center operator',
        regions: ['br-saopaulo', 'br-riodejaneiro'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Brazil', 'LGPD Compliance', 'PIX Integration'],
        recommendationReason: 'Direct PIX integration and BACEN compliance',
        avgCostPerMonth: 2500,
        supportedCurrencies: ['BRL', 'USD'],
        logo: '🇧🇷'
    },
    {
        id: 'kio',
        name: 'KIO Networks (Mexico)',
        country: 'Mexico',
        continent: 'North America',
        specialty: 'Mexican Market',
        description: 'Leading Mexican cloud and data center provider',
        regions: ['mx-mexicocity', 'mx-queretaro'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Mexico', 'CNBV Compliance', 'SPEI Integration'],
        recommendationReason: 'CNBV-approved for Mexican banking regulation',
        avgCostPerMonth: 2200,
        supportedCurrencies: ['MXN', 'USD'],
        logo: '🇲🇽'
    },

    // AFRICA
    {
        id: 'teraco',
        name: 'Teraco (South Africa)',
        country: 'South Africa',
        continent: 'Africa',
        specialty: 'African Data Hub',
        description: 'Largest African data center with undersea cable access',
        regions: ['za-johannesburg', 'za-capetown'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['South Africa', 'SARB Compliance', 'African Hub'],
        recommendationReason: 'Gateway to Africa with SARB regulatory approval',
        avgCostPerMonth: 2000,
        supportedCurrencies: ['ZAR', 'USD'],
        logo: '🇿🇦'
    },

    // OCEANIA
    {
        id: 'nextdc',
        name: 'NEXTDC (Australia)',
        country: 'Australia',
        continent: 'Oceania',
        specialty: 'Australian Tier IV',
        description: 'Premium Tier IV data centers across Australia',
        regions: ['au-sydney', 'au-melbourne', 'au-brisbane'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Australia', 'APRA Compliance', 'Banking'],
        recommendationReason: 'APRA-approved for Australian banking infrastructure',
        avgCostPerMonth: 3500,
        supportedCurrencies: ['AUD', 'USD'],
        logo: '🇦🇺'
    },

    // EDGE & CDN
    {
        id: 'cloudflare',
        name: 'Cloudflare',
        country: 'United States',
        continent: 'Global',
        specialty: 'Global Edge Network',
        description: '310+ cities, ultra-low latency edge computing',
        regions: ['global-edge'],
        tier: 'edge',
        pciDss: true,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Edge Computing', 'DDoS Protection', 'Global Distribution'],
        recommendationReason: 'Essential for DDoS protection and global payment routing',
        avgCostPerMonth: 1500,
        supportedCurrencies: ['USD'],
        logo: '🌐'
    },
    {
        id: 'akamai',
        name: 'Akamai',
        country: 'United States',
        continent: 'Global',
        specialty: 'Enterprise CDN',
        description: 'Largest CDN with payment optimization',
        regions: ['global-edge'],
        tier: 'edge',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Content Delivery', 'Payment APIs', 'Security'],
        recommendationReason: 'Battle-tested for high-volume payment traffic',
        avgCostPerMonth: 2500,
        supportedCurrencies: ['USD'],
        logo: '🚀'
    },

    // SPECIALTY PROVIDERS
    {
        id: 'digitalocean',
        name: 'DigitalOcean',
        country: 'United States',
        continent: 'Global',
        specialty: 'Developer-Friendly',
        description: 'Simple, affordable cloud for startups and SMEs',
        regions: ['nyc', 'sfo', 'ams', 'sgp', 'lon'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Startups', 'Development', 'SME PSPs'],
        recommendationReason: 'Best for early-stage PSPs and testing environments',
        avgCostPerMonth: 800,
        supportedCurrencies: ['USD'],
        logo: '🐳'
    },
    {
        id: 'linode',
        name: 'Linode (Akamai)',
        country: 'United States',
        continent: 'Global',
        specialty: 'VPS Leader',
        description: 'Reliable VPS with predictable pricing',
        regions: ['us', 'eu', 'ap', 'in'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['VPS Hosting', 'Backup Sites', 'DR'],
        recommendationReason: 'Excellent for disaster recovery and backup infrastructure',
        avgCostPerMonth: 600,
        supportedCurrencies: ['USD'],
        logo: '🖥️'
    },
    {
        id: 'vultr',
        name: 'Vultr',
        country: 'United States',
        continent: 'Global',
        specialty: 'High Performance',
        description: 'High-performance cloud with 32 global locations',
        regions: ['global'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Performance', 'Multi-Region', 'Bare Metal'],
        recommendationReason: 'High-performance instances for transaction processing',
        avgCostPerMonth: 900,
        supportedCurrencies: ['USD'],
        logo: '⚡'
    },

    // MORE NORTH AMERICA
    {
        id: 'ibm',
        name: 'IBM Cloud',
        country: 'United States',
        continent: 'North America',
        specialty: 'Mainframe & Legacy Integration',
        description: 'Enterprise cloud with mainframe connectivity',
        regions: ['us-south', 'us-east', 'eu-de', 'jp-tok'],
        tier: 'tier2',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Banking', 'Legacy Systems', 'Hybrid'],
        recommendationReason: 'Best for banks migrating from mainframes',
        avgCostPerMonth: 5000,
        supportedCurrencies: ['USD', 'EUR'],
        logo: '💙'
    },
    {
        id: 'rackspace',
        name: 'Rackspace',
        country: 'United States',
        continent: 'North America',
        specialty: 'Managed Services',
        description: 'Premium managed cloud hosting with 24/7 support',
        regions: ['us', 'uk', 'au'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Managed Services', 'Support', 'SME'],
        recommendationReason: 'Excellent for PSPs needing managed infrastructure',
        avgCostPerMonth: 3500,
        supportedCurrencies: ['USD'],
        logo: '🔧'
    },

    // MORE EUROPE
    {
        id: 'scaleway',
        name: 'Scaleway',
        country: 'France',
        continent: 'Europe',
        specialty: 'French Innovation',
        description: 'Innovative French cloud with eco-friendly data centers',
        regions: ['fr-par', 'nl-ams', 'pl-waw'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['France', 'Green Tech', 'Startups'],
        recommendationReason: 'Carbon-neutral hosting for sustainable PSPs',
        avgCostPerMonth: 1200,
        supportedCurrencies: ['EUR'],
        logo: '🌿'
    },
    {
        id: 'ionos',
        name: '1&1 IONOS',
        country: 'Germany',
        continent: 'Europe',
        specialty: 'European SME Cloud',
        description: 'Leading European hosting for small and medium businesses',
        regions: ['de-baden', 'us-lasvegas'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['SME', 'Europe', 'Web Hosting'],
        recommendationReason: 'Affordable European hosting with good support',
        avgCostPerMonth: 800,
        supportedCurrencies: ['EUR', 'USD'],
        logo: '🟦'
    },
    {
        id: 'tsystems',
        name: 'T-Systems (Sovereign)',
        country: 'Germany',
        continent: 'Europe',
        specialty: 'German Government Cloud',
        description: 'Deutsche Telekom sovereign cloud for government',
        regions: ['de-germany'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Government', 'BaFin', 'Sovereign'],
        recommendationReason: 'Required for German government PSP contracts',
        avgCostPerMonth: 5500,
        supportedCurrencies: ['EUR'],
        logo: '🇩🇪'
    },
    {
        id: 'aruba',
        name: 'Aruba Cloud (Italy)',
        country: 'Italy',
        continent: 'Europe',
        specialty: 'Italian Market',
        description: 'Leading Italian cloud provider with local support',
        regions: ['it-milan', 'it-arezzo'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Italy', 'Southern Europe'],
        recommendationReason: 'Best for Italian PSPs and local compliance',
        avgCostPerMonth: 1500,
        supportedCurrencies: ['EUR'],
        logo: '🇮🇹'
    },
    {
        id: 'telefonica',
        name: 'Telefónica Tech',
        country: 'Spain',
        continent: 'Europe',
        specialty: 'Spanish & LatAm',
        description: 'Spanish telco cloud with Latin America presence',
        regions: ['es-madrid', 'es-barcelona'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Spain', 'LatAm Bridge', 'Telco'],
        recommendationReason: 'Bridge between Europe and Latin America',
        avgCostPerMonth: 2000,
        supportedCurrencies: ['EUR'],
        logo: '🇪🇸'
    },
    {
        id: 'outscale',
        name: '3DS Outscale',
        country: 'France',
        continent: 'Europe',
        specialty: 'French Sovereign',
        description: 'Dassault Systèmes sovereign cloud for defense/finance',
        regions: ['eu-west'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Defense', 'Critical Infrastructure', 'Sovereign'],
        recommendationReason: 'Military-grade security for sensitive PSPs',
        avgCostPerMonth: 6000,
        supportedCurrencies: ['EUR'],
        logo: '🛡️'
    },
    {
        id: 'leaseweb',
        name: 'Leaseweb',
        country: 'Netherlands',
        continent: 'Europe',
        specialty: 'Dutch Hosting',
        description: 'Major Dutch hosting and cloud provider',
        regions: ['nl-amsterdam'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Netherlands', 'Hosting', 'Bare Metal'],
        recommendationReason: 'Excellent Amsterdam connectivity',
        avgCostPerMonth: 1300,
        supportedCurrencies: ['EUR'],
        logo: '🇳🇱'
    },
    {
        id: 'citynetwork',
        name: 'City Network',
        country: 'Sweden',
        continent: 'Europe',
        specialty: 'Nordic Cloud',
        description: 'Leading Nordic cloud provider',
        regions: ['se-stockholm'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Nordics', 'Sweden', 'Green Energy'],
        recommendationReason: '100% renewable energy powered',
        avgCostPerMonth: 1800,
        supportedCurrencies: ['SEK', 'EUR'],
        logo: '🇸🇪'
    },
    {
        id: 'contabo',
        name: 'Contabo',
        country: 'Germany',
        continent: 'Europe',
        specialty: 'Budget Cloud',
        description: 'Ultra-affordable German cloud hosting',
        regions: ['de-nuremberg', 'us-central'],
        tier: 'tier3',
        pciDss: false,
        iso27001: false,
        financialServices: false,
        recommendedFor: ['Budget', 'Testing', 'Non-Critical'],
        recommendationReason: 'Lowest cost option for development environments',
        avgCostPerMonth: 400,
        supportedCurrencies: ['EUR'],
        logo: '💸'
    },

    // MORE ASIA
    {
        id: 'baidu',
        name: 'Baidu Cloud',
        country: 'China',
        continent: 'Asia',
        specialty: 'AI & Search',
        description: 'Baidu AI and cloud infrastructure',
        regions: ['cn-beijing', 'cn-shanghai'],
        tier: 'tier3',
        pciDss: false,
        iso27001: false,
        financialServices: false,
        recommendedFor: ['China', 'AI', 'Analytics'],
        recommendationReason: 'Advanced AI for fraud detection',
        avgCostPerMonth: 2500,
        supportedCurrencies: ['CNY'],
        logo: '🔍'
    },
    {
        id: 'sakura',
        name: 'Sakura Internet',
        country: 'Japan',
        continent: 'Asia',
        specialty: 'Japanese Hosting',
        description: 'Major Japanese hosting and cloud provider',
        regions: ['jp-tokyo', 'jp-osaka'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Japan', 'Japanese PSPs'],
        recommendationReason: 'Local support and Japanese banking integrations',
        avgCostPerMonth: 1800,
        supportedCurrencies: ['JPY'],
        logo: '🌸'
    },
    {
        id: 'gmo',
        name: 'GMO Cloud',
        country: 'Japan',
        continent: 'Asia',
        specialty: 'Japanese Payment Gateway',
        description: 'GMO Payment Gateway cloud infrastructure',
        regions: ['jp-tokyo'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Japan', 'Payment Gateway'],
        recommendationReason: 'Direct GMO Payment Gateway integration',
        avgCostPerMonth: 2200,
        supportedCurrencies: ['JPY'],
        logo: '💳'
    },
    {
        id: 'kt',
        name: 'KT Cloud',
        country: 'South Korea',
        continent: 'Asia',
        specialty: 'Korean Telco',
        description: 'Korea Telecom enterprise cloud',
        regions: ['kr-seoul'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Korea', 'Enterprise'],
        recommendationReason: 'Korean banking sector preferred provider',
        avgCostPerMonth: 2300,
        supportedCurrencies: ['KRW'],
        logo: '📞'
    },
    {
        id: 'viettel',
        name: 'Viettel IDC',
        country: 'Vietnam',
        continent: 'Asia',
        specialty: 'Vietnam National',
        description: 'Vietnamese national telco and data centers',
        regions: ['vn-hanoi', 'vn-hochiminh'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Vietnam', 'Local Compliance'],
        recommendationReason: 'Required for Vietnamese data localization',
        avgCostPerMonth: 1200,
        supportedCurrencies: ['VND'],
        logo: '🇻🇳'
    },
    {
        id: 'ctrls',
        name: 'CtrlS Datacenters',
        country: 'India',
        continent: 'Asia',
        specialty: 'Indian Tier IV',
        description: 'Largest Tier IV data center in India',
        regions: ['in-mumbai', 'in-hyderabad'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['India', 'High Availability'],
        recommendationReason: 'Tier IV certification for mission-critical Indian PSPs',
        avgCostPerMonth: 2800,
        supportedCurrencies: ['INR'],
        logo: '🏢'
    },
    {
        id: 'sify',
        name: 'Sify Technologies',
        country: 'India',
        continent: 'Asia',
        specialty: 'Indian Enterprise',
        description: 'Enterprise cloud and managed services',
        regions: ['in-bangalore', 'in-chennai'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['India', 'Managed Services'],
        recommendationReason: 'Strong managed services for Indian market',
        avgCostPerMonth: 2000,
        supportedCurrencies: ['INR'],
        logo: '🇮🇳'
    },

    // MORE MIDDLE EAST
    {
        id: 'ooredoo',
        name: 'Ooredoo Cloud',
        country: 'Qatar',
        continent: 'Middle East',
        specialty: 'Qatar & GCC',
        description: 'Leading GCC telco cloud provider',
        regions: ['qa-doha'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Qatar', 'GCC', 'Telecom'],
        recommendationReason: 'GCC banking sector relationships',
        avgCostPerMonth: 3000,
        supportedCurrencies: ['QAR', 'USD'],
        logo: '🇶🇦'
    },
    {
        id: 'du',
        name: 'du Cloud',
        country: 'United Arab Emirates',
        continent: 'Middle East',
        specialty: 'UAE Telecom',
        description: 'UAE telecom cloud infrastructure',
        regions: ['ae-dubai'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['UAE', 'Telecom'],
        recommendationReason: 'Alternative UAE provider for redundancy',
        avgCostPerMonth: 3200,
        supportedCurrencies: ['AED'],
        logo: '📱'
    },

    // MORE LATIN AMERICA
    {
        id: 'scala',
        name: 'Scala Data Centers',
        country: 'Brazil',
        continent: 'South America',
        specialty: 'Brazilian Infrastructure',
        description: 'Major Brazilian hyperscale data centers',
        regions: ['br-saopaulo'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Brazil', 'Hyperscale'],
        recommendationReason: 'Hyperscale capacity for Brazilian growth',
        avgCostPerMonth: 2800,
        supportedCurrencies: ['BRL'],
        logo: '🇧🇷'
    },
    {
        id: 'layer9',
        name: 'Layer 9 (Argentina)',
        country: 'Argentina',
        continent: 'South America',
        specialty: 'Argentine Market',
        description: 'Argentine data centers and hosting',
        regions: ['ar-buenosaires'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Argentina', 'Regional'],
        recommendationReason: 'Local Argentine presence and compliance',
        avgCostPerMonth: 1500,
        supportedCurrencies: ['ARS'],
        logo: '🇦🇷'
    },

    // MORE AFRICA
    {
        id: 'mainone',
        name: 'MainOne',
        country: 'Nigeria',
        continent: 'Africa',
        specialty: 'West African Hub',
        description: 'Leading West African data center provider',
        regions: ['ng-lagos'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Nigeria', 'West Africa'],
        recommendationReason: 'Gateway to West African payment markets',
        avgCostPerMonth: 1800,
        supportedCurrencies: ['NGN', 'USD'],
        logo: '🇳🇬'
    },
    {
        id: 'rackcentre',
        name: 'Rack Centre',
        country: 'Nigeria',
        continent: 'Africa',
        specialty: 'Nigerian Banking',
        description: 'Nigerian cloud with banking certifications',
        regions: ['ng-lagos'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Nigeria', 'CBN Compliance'],
        recommendationReason: 'CBN-approved for Nigerian banking',
        avgCostPerMonth: 2000,
        supportedCurrencies: ['NGN'],
        logo: '🏦'
    },
    {
        id: 'africadc',
        name: 'Africa Data Centres',
        country: 'South Africa',
        continent: 'Africa',
        specialty: 'Pan-African',
        description: 'Pan-African data center network',
        regions: ['za-johannesburg', 'ke-nairobi'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Africa', 'Multi-Country'],
        recommendationReason: 'Multi-country African presence',
        avgCostPerMonth: 2200,
        supportedCurrencies: ['USD', 'ZAR'],
        logo: '🌍'
    },

    // MORE OCEANIA
    {
        id: 'airtrunk',
        name: 'AirTrunk',
        country: 'Australia',
        continent: 'Oceania',
        specialty: 'APAC Hyperscale',
        description: 'Asia-Pacific hyperscale data centers',
        regions: ['au-sydney', 'au-melbourne', 'sg-singapore', 'jp-tokyo'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Australia', 'APAC Hyperscale'],
        recommendationReason: 'Rapid APAC expansion and capacity',
        avgCostPerMonth: 3800,
        supportedCurrencies: ['AUD', 'USD'],
        logo: '💨'
    },
    {
        id: 'catalyst',
        name: 'Catalyst Cloud (NZ)',
        country: 'New Zealand',
        continent: 'Oceania',
        specialty: 'NZ Sovereign',
        description: 'New Zealand sovereign cloud',
        regions: ['nz-porirua', 'nz-auckland'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['New Zealand', 'Government', 'Sovereign'],
        recommendationReason: 'NZ government-certified sovereign cloud',
        avgCostPerMonth: 2500,
        supportedCurrencies: ['NZD'],
        logo: '🇳🇿'
    },
    {
        id: 'spark',
        name: 'Spark Cloud',
        country: 'New Zealand',
        continent: 'Oceania',
        specialty: 'NZ Telecom',
        description: 'New Zealand telecom cloud',
        regions: ['nz-auckland'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['New Zealand', 'Telco'],
        recommendationReason: 'NZ banking sector partnerships',
        avgCostPerMonth: 2300,
        supportedCurrencies: ['NZD'],
        logo: '⚡'
    },

    // MORE ASIA ADDITIONS
    {
        id: 'ncloud',
        name: 'Ncloud (NHN)',
        country: 'South Korea',
        continent: 'Asia',
        specialty: 'Korean Gaming',
        description: 'Korean cloud specialized in gaming and payments',
        regions: ['kr-seoul'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Gaming', 'Korea'],
        recommendationReason: 'Gaming payment expertise',
        avgCostPerMonth: 1800,
        supportedCurrencies: ['KRW'],
        logo: '🎮'
    },
    {
        id: 'starhub',
        name: 'StarHub Cloud',
        country: 'Singapore',
        continent: 'Asia',
        specialty: 'Singapore Telco',
        description: 'Singapore telecom cloud services',
        regions: ['sg-singapore'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Singapore', 'MAS Compliance'],
        recommendationReason: 'MAS-approved for Singapore PSPs',
        avgCostPerMonth: 2500,
        supportedCurrencies: ['SGD'],
        logo: '🌟'
    },
    {
        id: 'vnpt',
        name: 'VNPT Cloud',
        country: 'Vietnam',
        continent: 'Asia',
        specialty: 'Vietnam Telecom',
        description: 'Vietnam Posts and Telecom cloud',
        regions: ['vn-hanoi'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Vietnam'],
        recommendationReason: 'Government-backed Vietnamese provider',
        avgCostPerMonth: 1000,
        supportedCurrencies: ['VND'],
        logo: '📬'
    },

    // GOVERNMENT & SOVEREIGN
    {
        id: 'aws-gov',
        name: 'AWS GovCloud',
        country: 'United States',
        continent: 'North America',
        specialty: 'US Government',
        description: 'Isolated AWS regions for US government',
        regions: ['us-gov-west', 'us-gov-east'],
        tier: 'tier1',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Government', 'Defense', 'Critical'],
        recommendationReason: 'FedRAMP High certified for government PSPs',
        avgCostPerMonth: 8000,
        supportedCurrencies: ['USD'],
        logo: '🏛️'
    },
    {
        id: 'azure-gov',
        name: 'Azure Government',
        country: 'United States',
        continent: 'North America',
        specialty: 'US Government',
        description: 'Azure cloud for US government agencies',
        regions: ['usgov-virginia', 'usgov-texas'],
        tier: 'tier1',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Government', 'DoD', 'Federal'],
        recommendationReason: 'DoD Impact Level 5 certified',
        avgCostPerMonth: 8500,
        supportedCurrencies: ['USD'],
        logo: '🦅'
    },

    // ADDITIONAL PROVIDERS
    {
        id: 'equinix',
        name: 'Equinix Metal',
        country: 'United States',
        continent: 'Global',
        specialty: 'Bare Metal Global',
        description: 'Global interconnection and bare metal',
        regions: ['global'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Interconnection', 'Bare Metal', 'Low Latency'],
        recommendationReason: 'Best interconnection for multi-cloud and low-latency trading',
        avgCostPerMonth: 4000,
        supportedCurrencies: ['USD'],
        logo: '🔗'
    },
    {
        id: 'civo',
        name: 'Civo',
        country: 'United Kingdom',
        continent: 'Europe',
        specialty: 'Kubernetes Native',
        description: 'UK Kubernetes-native cloud',
        regions: ['uk-lon', 'us-nyc'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Kubernetes', 'Microservices', 'Startups'],
        recommendationReason: 'Fastest Kubernetes deployment',
        avgCostPerMonth: 700,
        supportedCurrencies: ['GBP', 'USD'],
        logo: '☸️'
    },
    {
        id: 'backblaze',
        name: 'Backblaze',
        country: 'United States',
        continent: 'North America',
        specialty: 'Object Storage',
        description: 'Ultra-affordable S3-compatible storage',
        regions: ['us', 'eu'],
        tier: 'tier3',
        pciDss: false,
        iso27001: false,
        financialServices: false,
        recommendedFor: ['Backup', 'Archive', 'Storage'],
        recommendationReason: 'Most affordable storage for transaction archives',
        avgCostPerMonth: 300,
        supportedCurrencies: ['USD'],
        logo: '💾'
    },
    {
        id: 'kamatera',
        name: 'Kamatera',
        country: 'Israel',
        continent: 'Middle East',
        specialty: 'Global VPS',
        description: 'Cloud VPS with 21 global data centers',
        regions: ['global'],
        tier: 'tier3',
        pciDss: false,
        iso27001: false,
        financialServices: false,
        recommendedFor: ['Global', 'VPS', 'Flexibility'],
        recommendationReason: 'Flexible hourly billing for dynamic workloads',
        avgCostPerMonth: 1000,
        supportedCurrencies: ['USD'],
        logo: '🌐'
    },
    {
        id: 'fastly',
        name: 'Fastly',
        country: 'United States',
        continent: 'Global',
        specialty: 'Real-time CDN',
        description: 'Real-time edge cloud platform',
        regions: ['global-edge'],
        tier: 'edge',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Edge', 'Real-time', 'CDN'],
        recommendationReason: 'Real-time purging for payment API edge delivery',
        avgCostPerMonth: 2000,
        supportedCurrencies: ['USD'],
        logo: '⚡'
    }
];

export const FILTER_OPTIONS = {
    continents: ['All', 'North America', 'South America', 'Europe', 'Asia', 'Africa', 'Middle East', 'Oceania', 'Global'],
    tiers: ['All', 'tier1', 'tier2', 'tier3', 'edge'],
    specialties: [
        'All',
        'Global Coverage',
        'Financial Compliance',
        'Data Sovereignty',
        'Cost-Effective',
        'Edge Computing',
        'Regional Leader',
        'Banking Infrastructure',
        'E-commerce',
        'Developer-Friendly'
    ],
    recommendations: [
        'All',
        'Mission Critical',
        'Enterprise',
        'China Market',
        'Europe',
        'Asia Pacific',
        'Middle East',
        'Latin America',
        'Africa',
        'Startups',
        'Development'
    ]
};

export const getTierLabel = (tier) => {
    const labels = {
        tier1: 'Tier 1 - Global Hyperscaler',
        tier2: 'Tier 2 - Regional Leader',
        tier3: 'Tier 3 - Specialized',
        edge: 'Edge Network'
    };
    return labels[tier] || tier;
};

export const getTierColor = (tier) => {
    const colors = {
        tier1: 'bg-purple-100 text-purple-700 border-purple-300',
        tier2: 'bg-blue-100 text-blue-700 border-blue-300',
        tier3: 'bg-cyan-100 text-cyan-700 border-cyan-300',
        edge: 'bg-pink-100 text-pink-700 border-pink-300'
    };
    return colors[tier] || 'bg-slate-100 text-slate-700';
};