// Comprehensive global cloud providers database for FTS.Money Platform
export const CLOUD_PROVIDERS = [
    // TIER 1 - GLOBAL HYPERSCALERS
    {
        id: 'aws',
        name: 'Amazon Web Services (AWS)',
        country: 'United States',
        continent: 'North America',
        specialty: 'Global Leader - Broadest Coverage',
        description: 'Industry leader with 33 regions, 105 availability zones worldwide',
        regions: ['us-east', 'us-west', 'eu-west', 'eu-central', 'ap-southeast', 'ap-northeast', 'sa-east', 'ca-central', 'me-south', 'af-south'],
        tier: 'tier1',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Mission Critical', 'Global Coverage', 'Financial Compliance'],
        recommendationReason: 'Best-in-class global infrastructure with proven financial services compliance',
        avgCostPerMonth: 5000,
        supportedCurrencies: ['USD', 'EUR', 'GBP', 'JPY', 'CNY'],
        logo: '☁️'
    },
    {
        id: 'azure',
        name: 'Microsoft Azure',
        country: 'United States',
        continent: 'North America',
        specialty: 'Enterprise Integration - Microsoft Stack',
        description: 'Strong enterprise compliance and hybrid cloud capabilities',
        regions: ['eastus', 'westus', 'northeurope', 'westeurope', 'southeastasia', 'australiaeast'],
        tier: 'tier1',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Enterprise', 'Hybrid Cloud', 'Government'],
        recommendationReason: 'Excellent for enterprise compliance, sovereign cloud options',
        avgCostPerMonth: 4800,
        supportedCurrencies: ['USD', 'EUR', 'GBP'],
        logo: '⊞'
    },
    {
        id: 'gcp',
        name: 'Google Cloud Platform (GCP)',
        country: 'United States',
        continent: 'North America',
        specialty: 'AI/ML & Advanced Analytics',
        description: 'Leading in AI, machine learning, and payment processing technology',
        regions: ['us-central', 'us-east', 'europe-west', 'asia-southeast'],
        tier: 'tier1',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['AI/ML', 'Payment Processing', 'Real-time Analytics'],
        recommendationReason: 'Superior payment processing APIs and real-time fraud detection',
        avgCostPerMonth: 4500,
        supportedCurrencies: ['USD', 'EUR'],
        logo: '🔵'
    },

    // TIER 2 - REGIONAL LEADERS
    {
        id: 'alibaba',
        name: 'Alibaba Cloud',
        country: 'China',
        continent: 'Asia',
        specialty: 'Asia Pacific Dominance',
        description: 'Largest cloud provider in Asia with deep China penetration',
        regions: ['cn-hangzhou', 'cn-beijing', 'cn-shanghai', 'ap-southeast', 'ap-northeast'],
        tier: 'tier2',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['China Market', 'Asia Pacific', 'Cross-border Payments'],
        recommendationReason: 'Essential for China operations and Asian e-commerce integration',
        avgCostPerMonth: 3500,
        supportedCurrencies: ['CNY', 'USD', 'EUR'],
        logo: '🟠'
    },
    {
        id: 'tencent',
        name: 'Tencent Cloud (腾讯云)',
        country: 'China',
        continent: 'Asia',
        specialty: 'WeChat & Gaming Infrastructure',
        description: 'Deep integration with WeChat Pay and Chinese digital ecosystem',
        regions: ['ap-guangzhou', 'ap-beijing', 'ap-shanghai', 'ap-nanjing'],
        tier: 'tier2',
        pciDss: true,
        iso27001: false,
        financialServices: true,
        recommendedFor: ['WeChat Integration', 'Gaming', 'Social Payments'],
        recommendationReason: 'Direct WeChat Pay integration and massive user base access',
        avgCostPerMonth: 3200,
        supportedCurrencies: ['CNY', 'HKD'],
        logo: '🐧'
    },
    {
        id: 'huawei',
        name: 'Huawei Cloud (华为云)',
        country: 'China',
        continent: 'Asia',
        specialty: '5G & Edge Computing',
        description: 'Leading in 5G infrastructure and telecom-grade reliability',
        regions: ['cn-north', 'cn-east', 'cn-south', 'ap-southeast'],
        tier: 'tier2',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Telecom', '5G Edge', 'IoT Payments'],
        recommendationReason: '5G-enabled edge computing for ultra-low latency transactions',
        avgCostPerMonth: 3000,
        supportedCurrencies: ['CNY', 'USD'],
        logo: '📡'
    },
    {
        id: 'ovhcloud',
        name: 'OVHcloud',
        country: 'France',
        continent: 'Europe',
        specialty: 'European Sovereignty',
        description: 'Largest European cloud provider with GDPR-native architecture',
        regions: ['eu-west', 'eu-central', 'ca-east'],
        tier: 'tier2',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['GDPR Compliance', 'EU Data Sovereignty', 'European PSPs'],
        recommendationReason: 'Best European sovereign cloud option with competitive pricing',
        avgCostPerMonth: 2800,
        supportedCurrencies: ['EUR', 'USD', 'GBP'],
        logo: '🇫🇷'
    },
    {
        id: 'oracle',
        name: 'Oracle Cloud',
        country: 'United States',
        continent: 'North America',
        specialty: 'Database & Financial Systems',
        description: 'Enterprise-grade database and financial application hosting',
        regions: ['us-phoenix', 'us-ashburn', 'eu-frankfurt', 'ap-mumbai'],
        tier: 'tier2',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Banking', 'Core Banking Systems', 'Oracle Applications'],
        recommendationReason: 'Native Oracle database integration and banking expertise',
        avgCostPerMonth: 4000,
        supportedCurrencies: ['USD', 'EUR'],
        logo: '🔴'
    },

    // ASIA PACIFIC
    {
        id: 'ntt',
        name: 'NTT Communications',
        country: 'Japan',
        continent: 'Asia',
        specialty: 'Japanese Enterprise',
        description: 'Leading Japanese cloud with strong financial sector presence',
        regions: ['jp-tokyo', 'jp-osaka'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Japan Market', 'Japanese Banking', 'Local Compliance'],
        recommendationReason: 'Deep relationships with Japanese financial institutions',
        avgCostPerMonth: 3500,
        supportedCurrencies: ['JPY', 'USD'],
        logo: '🇯🇵'
    },
    {
        id: 'naver',
        name: 'Naver Cloud',
        country: 'South Korea',
        continent: 'Asia',
        specialty: 'Korean E-commerce',
        description: 'Dominant in Korean market with Naver Pay integration',
        regions: ['kr-seoul'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Korea Market', 'Naver Pay', 'K-commerce'],
        recommendationReason: 'Essential for Korean PSPs and Naver ecosystem',
        avgCostPerMonth: 2500,
        supportedCurrencies: ['KRW', 'USD'],
        logo: '🇰🇷'
    },
    {
        id: 'singtel',
        name: 'Singtel Cloud',
        country: 'Singapore',
        continent: 'Asia',
        specialty: 'ASEAN Connectivity',
        description: 'Regional connectivity across Southeast Asia',
        regions: ['sg-singapore'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Singapore', 'ASEAN', 'Regional Payments'],
        recommendationReason: 'Excellent ASEAN network connectivity and local banking ties',
        avgCostPerMonth: 2800,
        supportedCurrencies: ['SGD', 'USD'],
        logo: '🇸🇬'
    },
    {
        id: 'tata',
        name: 'Tata Communications',
        country: 'India',
        continent: 'Asia',
        specialty: 'Indian Market Leader',
        description: 'Largest Indian cloud provider with RBI compliance',
        regions: ['in-mumbai', 'in-chennai', 'in-hyderabad'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['India Market', 'RBI Compliance', 'UPI Integration'],
        recommendationReason: 'RBI-approved infrastructure with UPI gateway access',
        avgCostPerMonth: 2000,
        supportedCurrencies: ['INR', 'USD'],
        logo: '🇮🇳'
    },
    {
        id: 'telkom',
        name: 'Telkom Indonesia',
        country: 'Indonesia',
        continent: 'Asia',
        specialty: 'Indonesia National Cloud',
        description: 'National telco with government cloud contracts',
        regions: ['id-jakarta'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Indonesia', 'Government', 'Local PSPs'],
        recommendationReason: 'Required for Indonesian data localization laws',
        avgCostPerMonth: 1800,
        supportedCurrencies: ['IDR', 'USD'],
        logo: '🇮🇩'
    },

    // MIDDLE EAST
    {
        id: 'stc',
        name: 'STC Cloud (Saudi)',
        country: 'Saudi Arabia',
        continent: 'Middle East',
        specialty: 'Saudi Banking Infrastructure',
        description: 'SAMA-approved cloud for Saudi financial services',
        regions: ['sa-riyadh', 'sa-jeddah'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Saudi Arabia', 'SAMA Compliance', 'Islamic Finance'],
        recommendationReason: 'SAMA-certified with Sharia-compliant hosting options',
        avgCostPerMonth: 3200,
        supportedCurrencies: ['SAR', 'USD'],
        logo: '🇸🇦'
    },
    {
        id: 'etisalat',
        name: 'Etisalat Cloud (UAE)',
        country: 'United Arab Emirates',
        continent: 'Middle East',
        specialty: 'UAE Financial Hub',
        description: 'Dubai financial free zone certified infrastructure',
        regions: ['ae-dubai', 'ae-abudhabi'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['UAE', 'DIFC Compliance', 'Middle East Hub'],
        recommendationReason: 'DIFC-certified for Dubai International Financial Centre',
        avgCostPerMonth: 3500,
        supportedCurrencies: ['AED', 'USD'],
        logo: '🇦🇪'
    },

    // EUROPE
    {
        id: 'stackit',
        name: 'STACKIT (Sovereign)',
        country: 'Germany',
        continent: 'Europe',
        specialty: 'German Sovereign Cloud',
        description: 'Schwarz Group sovereign cloud for German data residency',
        regions: ['de-germany'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Germany', 'BaFin Compliance', 'Data Sovereignty'],
        recommendationReason: 'Only sovereign cloud meeting strict German banking regulations',
        avgCostPerMonth: 4000,
        supportedCurrencies: ['EUR'],
        logo: '🇩🇪'
    },
    {
        id: 'exoscale',
        name: 'Exoscale (Swiss)',
        country: 'Switzerland',
        continent: 'Europe',
        specialty: 'Swiss Banking Standards',
        description: 'Swiss sovereign cloud with banking-grade security',
        regions: ['ch-zurich', 'ch-geneva'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Switzerland', 'Private Banking', 'FINMA Compliance'],
        recommendationReason: 'Swiss privacy laws and banking sector expertise',
        avgCostPerMonth: 4500,
        supportedCurrencies: ['CHF', 'EUR'],
        logo: '🇨🇭'
    },
    {
        id: 'hetzner',
        name: 'Hetzner',
        country: 'Germany',
        continent: 'Europe',
        specialty: 'Cost-Effective European',
        description: 'Budget-friendly German hosting with excellent performance',
        regions: ['de-falkenstein', 'de-nuremberg', 'fi-helsinki'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Cost Optimization', 'SME PSPs', 'Development'],
        recommendationReason: 'Best price-performance ratio in Europe',
        avgCostPerMonth: 1000,
        supportedCurrencies: ['EUR'],
        logo: '💰'
    },

    // LATIN AMERICA
    {
        id: 'ascenty',
        name: 'Ascenty (Brazil)',
        country: 'Brazil',
        continent: 'South America',
        specialty: 'Brazilian Data Centers',
        description: 'Largest Brazilian data center operator',
        regions: ['br-saopaulo', 'br-riodejaneiro'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Brazil', 'LGPD Compliance', 'PIX Integration'],
        recommendationReason: 'Direct PIX integration and BACEN compliance',
        avgCostPerMonth: 2500,
        supportedCurrencies: ['BRL', 'USD'],
        logo: '🇧🇷'
    },
    {
        id: 'kio',
        name: 'KIO Networks (Mexico)',
        country: 'Mexico',
        continent: 'North America',
        specialty: 'Mexican Market',
        description: 'Leading Mexican cloud and data center provider',
        regions: ['mx-mexicocity', 'mx-queretaro'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Mexico', 'CNBV Compliance', 'SPEI Integration'],
        recommendationReason: 'CNBV-approved for Mexican banking regulation',
        avgCostPerMonth: 2200,
        supportedCurrencies: ['MXN', 'USD'],
        logo: '🇲🇽'
    },

    // AFRICA
    {
        id: 'teraco',
        name: 'Teraco (South Africa)',
        country: 'South Africa',
        continent: 'Africa',
        specialty: 'African Data Hub',
        description: 'Largest African data center with undersea cable access',
        regions: ['za-johannesburg', 'za-capetown'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['South Africa', 'SARB Compliance', 'African Hub'],
        recommendationReason: 'Gateway to Africa with SARB regulatory approval',
        avgCostPerMonth: 2000,
        supportedCurrencies: ['ZAR', 'USD'],
        logo: '🇿🇦'
    },

    // OCEANIA
    {
        id: 'nextdc',
        name: 'NEXTDC (Australia)',
        country: 'Australia',
        continent: 'Oceania',
        specialty: 'Australian Tier IV',
        description: 'Premium Tier IV data centers across Australia',
        regions: ['au-sydney', 'au-melbourne', 'au-brisbane'],
        tier: 'tier3',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Australia', 'APRA Compliance', 'Banking'],
        recommendationReason: 'APRA-approved for Australian banking infrastructure',
        avgCostPerMonth: 3500,
        supportedCurrencies: ['AUD', 'USD'],
        logo: '🇦🇺'
    },

    // EDGE & CDN
    {
        id: 'cloudflare',
        name: 'Cloudflare',
        country: 'United States',
        continent: 'Global',
        specialty: 'Global Edge Network',
        description: '310+ cities, ultra-low latency edge computing',
        regions: ['global-edge'],
        tier: 'edge',
        pciDss: true,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Edge Computing', 'DDoS Protection', 'Global Distribution'],
        recommendationReason: 'Essential for DDoS protection and global payment routing',
        avgCostPerMonth: 1500,
        supportedCurrencies: ['USD'],
        logo: '🌐'
    },
    {
        id: 'akamai',
        name: 'Akamai',
        country: 'United States',
        continent: 'Global',
        specialty: 'Enterprise CDN',
        description: 'Largest CDN with payment optimization',
        regions: ['global-edge'],
        tier: 'edge',
        pciDss: true,
        iso27001: true,
        financialServices: true,
        recommendedFor: ['Content Delivery', 'Payment APIs', 'Security'],
        recommendationReason: 'Battle-tested for high-volume payment traffic',
        avgCostPerMonth: 2500,
        supportedCurrencies: ['USD'],
        logo: '🚀'
    },

    // SPECIALTY PROVIDERS
    {
        id: 'digitalocean',
        name: 'DigitalOcean',
        country: 'United States',
        continent: 'Global',
        specialty: 'Developer-Friendly',
        description: 'Simple, affordable cloud for startups and SMEs',
        regions: ['nyc', 'sfo', 'ams', 'sgp', 'lon'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Startups', 'Development', 'SME PSPs'],
        recommendationReason: 'Best for early-stage PSPs and testing environments',
        avgCostPerMonth: 800,
        supportedCurrencies: ['USD'],
        logo: '🐳'
    },
    {
        id: 'linode',
        name: 'Linode (Akamai)',
        country: 'United States',
        continent: 'Global',
        specialty: 'VPS Leader',
        description: 'Reliable VPS with predictable pricing',
        regions: ['us', 'eu', 'ap', 'in'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['VPS Hosting', 'Backup Sites', 'DR'],
        recommendationReason: 'Excellent for disaster recovery and backup infrastructure',
        avgCostPerMonth: 600,
        supportedCurrencies: ['USD'],
        logo: '🖥️'
    },
    {
        id: 'vultr',
        name: 'Vultr',
        country: 'United States',
        continent: 'Global',
        specialty: 'High Performance',
        description: 'High-performance cloud with 32 global locations',
        regions: ['global'],
        tier: 'tier3',
        pciDss: false,
        iso27001: true,
        financialServices: false,
        recommendedFor: ['Performance', 'Multi-Region', 'Bare Metal'],
        recommendationReason: 'High-performance instances for transaction processing',
        avgCostPerMonth: 900,
        supportedCurrencies: ['USD'],
        logo: '⚡'
    }
];

export const FILTER_OPTIONS = {
    continents: ['All', 'North America', 'South America', 'Europe', 'Asia', 'Africa', 'Middle East', 'Oceania', 'Global'],
    tiers: ['All', 'tier1', 'tier2', 'tier3', 'edge'],
    specialties: [
        'All',
        'Global Coverage',
        'Financial Compliance',
        'Data Sovereignty',
        'Cost-Effective',
        'Edge Computing',
        'Regional Leader',
        'Banking Infrastructure',
        'E-commerce',
        'Developer-Friendly'
    ],
    recommendations: [
        'All',
        'Mission Critical',
        'Enterprise',
        'China Market',
        'Europe',
        'Asia Pacific',
        'Middle East',
        'Latin America',
        'Africa',
        'Startups',
        'Development'
    ]
};

export const getTierLabel = (tier) => {
    const labels = {
        tier1: 'Tier 1 - Global Hyperscaler',
        tier2: 'Tier 2 - Regional Leader',
        tier3: 'Tier 3 - Specialized',
        edge: 'Edge Network'
    };
    return labels[tier] || tier;
};

export const getTierColor = (tier) => {
    const colors = {
        tier1: 'bg-purple-100 text-purple-700 border-purple-300',
        tier2: 'bg-blue-100 text-blue-700 border-blue-300',
        tier3: 'bg-cyan-100 text-cyan-700 border-cyan-300',
        edge: 'bg-pink-100 text-pink-700 border-pink-300'
    };
    return colors[tier] || 'bg-slate-100 text-slate-700';
};