/**
 * Crypto Banking Gateway RBAC - Permission Registry
 */

export const CRYPTO_PERMISSIONS = {
    // Customer Management
    CUSTOMER_READ: 'customer:read',
    CUSTOMER_UPDATE: 'customer:update',
    CUSTOMER_BILLING: 'customer:billing',
    
    // Wallet Management
    WALLET_CREATE: 'wallet:create',
    WALLET_VIEW: 'wallet:view',
    WALLET_TRANSACTIONS: 'wallet:transactions',
    WALLET_WITHDRAW: 'wallet:withdraw',
    
    // IBAN Management
    IBAN_CREATE: 'iban:create',
    IBAN_VIEW: 'iban:view',
    IBAN_MANAGE: 'iban:manage',
    
    // Transactions
    TRANSACTION_VIEW: 'transaction:view',
    TRANSACTION_EXPORT: 'transaction:export',
    TRANSACTION_INITIATE: 'transaction:initiate',
    
    // KYC/Compliance
    KYC_VIEW: 'kyc:view',
    KYC_APPROVE: 'kyc:approve',
    KYC_DOCUMENTS: 'kyc:documents',
    
    // Cards
    CARD_CREATE: 'card:create',
    CARD_VIEW: 'card:view',
    CARD_MANAGE: 'card:manage',
    
    // API Access
    API_KEYS_MANAGE: 'api:keys_manage',
    API_DOCS_VIEW: 'api:docs_view',
    API_LOGS_VIEW: 'api:logs_view',
    
    // User Management
    USER_INVITE: 'user:invite',
    USER_MANAGE: 'user:manage',
    USER_DELETE: 'user:delete',
    
    // Analytics
    ANALYTICS_VIEW: 'analytics:view',
    ANALYTICS_EXPORT: 'analytics:export'
};

export const CRYPTO_ROLES = {
    OWNER: 'owner',
    ADMINISTRATOR: 'administrator',
    COMPLIANCE_OFFICER: 'compliance_officer',
    DEVELOPER: 'developer',
    OPERATIONS: 'operations',
    ANALYST: 'analyst',
    VIEWER: 'viewer'
};

export const CRYPTO_ROLE_PERMISSIONS = {
    [CRYPTO_ROLES.OWNER]: Object.values(CRYPTO_PERMISSIONS),
    
    [CRYPTO_ROLES.ADMINISTRATOR]: [
        CRYPTO_PERMISSIONS.CUSTOMER_READ,
        CRYPTO_PERMISSIONS.CUSTOMER_UPDATE,
        CRYPTO_PERMISSIONS.WALLET_CREATE,
        CRYPTO_PERMISSIONS.WALLET_VIEW,
        CRYPTO_PERMISSIONS.WALLET_TRANSACTIONS,
        CRYPTO_PERMISSIONS.WALLET_WITHDRAW,
        CRYPTO_PERMISSIONS.IBAN_CREATE,
        CRYPTO_PERMISSIONS.IBAN_VIEW,
        CRYPTO_PERMISSIONS.IBAN_MANAGE,
        CRYPTO_PERMISSIONS.TRANSACTION_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_EXPORT,
        CRYPTO_PERMISSIONS.TRANSACTION_INITIATE,
        CRYPTO_PERMISSIONS.KYC_VIEW,
        CRYPTO_PERMISSIONS.KYC_APPROVE,
        CRYPTO_PERMISSIONS.KYC_DOCUMENTS,
        CRYPTO_PERMISSIONS.CARD_CREATE,
        CRYPTO_PERMISSIONS.CARD_VIEW,
        CRYPTO_PERMISSIONS.CARD_MANAGE,
        CRYPTO_PERMISSIONS.API_KEYS_MANAGE,
        CRYPTO_PERMISSIONS.API_DOCS_VIEW,
        CRYPTO_PERMISSIONS.API_LOGS_VIEW,
        CRYPTO_PERMISSIONS.USER_INVITE,
        CRYPTO_PERMISSIONS.USER_MANAGE,
        CRYPTO_PERMISSIONS.ANALYTICS_VIEW,
        CRYPTO_PERMISSIONS.ANALYTICS_EXPORT
    ],
    
    [CRYPTO_ROLES.COMPLIANCE_OFFICER]: [
        CRYPTO_PERMISSIONS.CUSTOMER_READ,
        CRYPTO_PERMISSIONS.WALLET_VIEW,
        CRYPTO_PERMISSIONS.WALLET_TRANSACTIONS,
        CRYPTO_PERMISSIONS.TRANSACTION_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_EXPORT,
        CRYPTO_PERMISSIONS.KYC_VIEW,
        CRYPTO_PERMISSIONS.KYC_APPROVE,
        CRYPTO_PERMISSIONS.KYC_DOCUMENTS,
        CRYPTO_PERMISSIONS.ANALYTICS_VIEW,
        CRYPTO_PERMISSIONS.ANALYTICS_EXPORT
    ],
    
    [CRYPTO_ROLES.DEVELOPER]: [
        CRYPTO_PERMISSIONS.CUSTOMER_READ,
        CRYPTO_PERMISSIONS.WALLET_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_VIEW,
        CRYPTO_PERMISSIONS.API_KEYS_MANAGE,
        CRYPTO_PERMISSIONS.API_DOCS_VIEW,
        CRYPTO_PERMISSIONS.API_LOGS_VIEW
    ],
    
    [CRYPTO_ROLES.OPERATIONS]: [
        CRYPTO_PERMISSIONS.CUSTOMER_READ,
        CRYPTO_PERMISSIONS.WALLET_VIEW,
        CRYPTO_PERMISSIONS.WALLET_TRANSACTIONS,
        CRYPTO_PERMISSIONS.IBAN_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_EXPORT,
        CRYPTO_PERMISSIONS.CARD_VIEW,
        CRYPTO_PERMISSIONS.API_LOGS_VIEW,
        CRYPTO_PERMISSIONS.ANALYTICS_VIEW
    ],
    
    [CRYPTO_ROLES.ANALYST]: [
        CRYPTO_PERMISSIONS.CUSTOMER_READ,
        CRYPTO_PERMISSIONS.WALLET_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_VIEW,
        CRYPTO_PERMISSIONS.ANALYTICS_VIEW,
        CRYPTO_PERMISSIONS.ANALYTICS_EXPORT
    ],
    
    [CRYPTO_ROLES.VIEWER]: [
        CRYPTO_PERMISSIONS.CUSTOMER_READ,
        CRYPTO_PERMISSIONS.WALLET_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_VIEW,
        CRYPTO_PERMISSIONS.ANALYTICS_VIEW
    ]
};

export const CRYPTO_ROLE_HIERARCHY = {
    [CRYPTO_ROLES.OWNER]: 100,
    [CRYPTO_ROLES.ADMINISTRATOR]: 80,
    [CRYPTO_ROLES.COMPLIANCE_OFFICER]: 70,
    [CRYPTO_ROLES.DEVELOPER]: 60,
    [CRYPTO_ROLES.OPERATIONS]: 50,
    [CRYPTO_ROLES.ANALYST]: 40,
    [CRYPTO_ROLES.VIEWER]: 20
};

export function hasCryptoPermission(role, permission) {
    return (CRYPTO_ROLE_PERMISSIONS[role] || []).includes(permission);
}

export function getCryptoRoleLabel(role) {
    const labels = {
        [CRYPTO_ROLES.OWNER]: 'Owner',
        [CRYPTO_ROLES.ADMINISTRATOR]: 'Administrator',
        [CRYPTO_ROLES.COMPLIANCE_OFFICER]: 'Compliance Officer',
        [CRYPTO_ROLES.DEVELOPER]: 'Developer',
        [CRYPTO_ROLES.OPERATIONS]: 'Operations',
        [CRYPTO_ROLES.ANALYST]: 'Analyst',
        [CRYPTO_ROLES.VIEWER]: 'Viewer'
    };
    return labels[role] || role;
}