export const CRYPTO_ROLES = {
    OWNER: 'owner',
    ADMINISTRATOR: 'administrator',
    DEVELOPER: 'developer',
    OPERATIONS: 'operations',
    ANALYST: 'analyst',
    VIEWER: 'viewer'
};

export const CRYPTO_PERMISSIONS = {
    CUSTOMER_VIEW: 'customer:view',
    CUSTOMER_UPDATE: 'customer:update',
    WALLET_VIEW: 'wallet:view',
    WALLET_CREATE: 'wallet:create',
    WALLET_UPDATE: 'wallet:update',
    TRANSACTION_VIEW: 'transaction:view',
    TRANSACTION_CREATE: 'transaction:create',
    KYC_VIEW: 'kyc:view',
    KYC_APPROVE: 'kyc:approve',
    KYC_REJECT: 'kyc:reject',
    IBAN_VIEW: 'iban:view',
    IBAN_CREATE: 'iban:create',
    API_KEY_VIEW: 'api_key:view',
    API_KEY_CREATE: 'api_key:create',
    API_KEY_DELETE: 'api_key:delete',
    ANALYTICS_VIEW: 'analytics:view',
    BILLING_VIEW: 'billing:view',
    SETTINGS_UPDATE: 'settings:update',
    USER_MANAGE: 'user:manage'
};

export const CRYPTO_ROLE_PERMISSIONS = {
    [CRYPTO_ROLES.OWNER]: Object.values(CRYPTO_PERMISSIONS),
    [CRYPTO_ROLES.ADMINISTRATOR]: [
        CRYPTO_PERMISSIONS.CUSTOMER_VIEW,
        CRYPTO_PERMISSIONS.CUSTOMER_UPDATE,
        CRYPTO_PERMISSIONS.WALLET_VIEW,
        CRYPTO_PERMISSIONS.WALLET_CREATE,
        CRYPTO_PERMISSIONS.WALLET_UPDATE,
        CRYPTO_PERMISSIONS.TRANSACTION_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_CREATE,
        CRYPTO_PERMISSIONS.KYC_VIEW,
        CRYPTO_PERMISSIONS.KYC_APPROVE,
        CRYPTO_PERMISSIONS.KYC_REJECT,
        CRYPTO_PERMISSIONS.IBAN_VIEW,
        CRYPTO_PERMISSIONS.IBAN_CREATE,
        CRYPTO_PERMISSIONS.API_KEY_VIEW,
        CRYPTO_PERMISSIONS.API_KEY_CREATE,
        CRYPTO_PERMISSIONS.ANALYTICS_VIEW,
        CRYPTO_PERMISSIONS.BILLING_VIEW,
        CRYPTO_PERMISSIONS.SETTINGS_UPDATE,
        CRYPTO_PERMISSIONS.USER_MANAGE
    ],
    [CRYPTO_ROLES.DEVELOPER]: [
        CRYPTO_PERMISSIONS.CUSTOMER_VIEW,
        CRYPTO_PERMISSIONS.WALLET_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_VIEW,
        CRYPTO_PERMISSIONS.API_KEY_VIEW,
        CRYPTO_PERMISSIONS.API_KEY_CREATE,
        CRYPTO_PERMISSIONS.ANALYTICS_VIEW
    ],
    [CRYPTO_ROLES.OPERATIONS]: [
        CRYPTO_PERMISSIONS.CUSTOMER_VIEW,
        CRYPTO_PERMISSIONS.WALLET_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_VIEW,
        CRYPTO_PERMISSIONS.KYC_VIEW,
        CRYPTO_PERMISSIONS.IBAN_VIEW,
        CRYPTO_PERMISSIONS.ANALYTICS_VIEW
    ],
    [CRYPTO_ROLES.ANALYST]: [
        CRYPTO_PERMISSIONS.CUSTOMER_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_VIEW,
        CRYPTO_PERMISSIONS.ANALYTICS_VIEW,
        CRYPTO_PERMISSIONS.BILLING_VIEW
    ],
    [CRYPTO_ROLES.VIEWER]: [
        CRYPTO_PERMISSIONS.CUSTOMER_VIEW,
        CRYPTO_PERMISSIONS.WALLET_VIEW,
        CRYPTO_PERMISSIONS.TRANSACTION_VIEW,
        CRYPTO_PERMISSIONS.ANALYTICS_VIEW
    ]
};

export function getCryptoRoleLabel(role) {
    const labels = {
        [CRYPTO_ROLES.OWNER]: 'Owner',
        [CRYPTO_ROLES.ADMINISTRATOR]: 'Administrator',
        [CRYPTO_ROLES.DEVELOPER]: 'Developer',
        [CRYPTO_ROLES.OPERATIONS]: 'Operations',
        [CRYPTO_ROLES.ANALYST]: 'Analyst',
        [CRYPTO_ROLES.VIEWER]: 'Viewer'
    };
    return labels[role] || role;
}